schema_version = "1.0.0"

id = "MoveYoNode"
version = "1.0.0"
name = "Move yo' Node"
tagline = "Organize node groups with dependencies into a file hierarchy"
maintainer = "Romain Guimbal"
type = "add-on"

website = "https://github.com/RomainGuimbal/Node-Organizer"

tags = ["Geometry Nodes"]

blender_version_min = "5.2.0"

license = ["SPDX:GPL-3.0-or-later"]

copyright = ["2026 Romain Guimbal"]

wheels = ["./wheels/cadquery_ocp_novtk-7.9.3.1-cp313-cp313-win_amd64.whl"]

[permissions]
files = "Create and open blend files"